In [3]:
#Create two 3×3 matrices using the random function in Numpy and perform the following operations.
#è Product (prod)
#è Multiplication (multiply)
#è Dot Product (dot) 

import numpy as np

# Create two 3x3 matrices
matrix1 = np.random.randint(10, size=(3, 3))
matrix2 = np.random.randint(10, size=(3, 3))

# Print the matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Calculate the product of the matrices
product = np.dot(matrix1, matrix2)

# Print the product
print("\nProduct of the matrices:")
print(product)

# Calculate the multiplication of the matrices
multiplication = matrix1 * matrix2

# Print the multiplication
print("\nMultiplication of the matrices:")
print(multiplication)

# Calculate the dot product of the matrices
dot_product = np.matmul(matrix1, matrix2)

# Print the dot product
print("\nDot product of the matrices:")
print(dot_product)

Matrix 1:
[[0 7 6]
 [4 3 7]
 [0 8 3]]

Matrix 2:
[[4 4 2]
 [1 1 1]
 [4 9 2]]

Product of the matrices:
[[31 61 19]
 [47 82 25]
 [20 35 14]]

Multiplication of the matrices:
[[ 0 28 12]
 [ 4  3  7]
 [ 0 72  6]]

Dot product of the matrices:
[[31 61 19]
 [47 82 25]
 [20 35 14]]


Perform the following set operations using the Numpy functions.
- Union
- Intersection
- Set difference
- XOR

In [4]:
import numpy as np

# Create two sets
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

# Print the sets
print("Set 1:")
print(set1)
print("\nSet 2:")
print(set2)

# Calculate the union of the sets
union = np.union1d(set1, set2)

# Print the union
print("\nUnion of the sets:")
print(union)

# Calculate the intersection of the sets
intersection = np.intersect1d(set1, set2)

# Print the intersection
print("\nIntersection of the sets:")
print(intersection)

# Calculate the set difference of set1 and set2
set_difference1 = np.setdiff1d(set1, set2)

# Print the set difference
print("\nSet difference of set1 and set2:")
print(set_difference1)


# Calculate the XOR of the sets
xor = np.setxor1d(set1, set2)

# Print the XOR
print("\nXOR of the sets:")
print(xor)


Set 1:
[1 2 3 4 5]

Set 2:
[3 4 5 6 7]

Union of the sets:
[1 2 3 4 5 6 7]

Intersection of the sets:
[3 4 5]

Set difference of set1 and set2:
[1 2]

XOR of the sets:
[1 2 6 7]


Create a 1D array using Random function and perform the following operations.
- Cumulative sum
- Cumulative Product
- Discrete difference (with n=3)
- Find the unique elements from the array

In [5]:
import numpy as np

# Create a 1D array with 10 elements
array = np.random.randint(10, size=10)

# Print the array
print("Array:")
print(array)

# Calculate the cumulative sum of the array
cumulative_sum = np.cumsum(array)

# Print the cumulative sum
print("\nCumulative sum:")
print(cumulative_sum)

# Calculate the cumulative product of the array
cumulative_product = np.cumprod(array)

# Print the cumulative product
print("\nCumulative product:")
print(cumulative_product)

# Calculate the discrete difference of the array with n=3
discrete_difference = np.diff(array, n=3)

# Print the discrete difference
print("\nDiscrete difference (n=3):")
print(discrete_difference)

# Find the unique elements from the array
unique_elements = np.unique(array)

# Print the unique elements
print("\nUnique elements:")
print(unique_elements)


Array:
[4 8 5 3 9 2 5 0 7 5]

Cumulative sum:
[ 4 12 17 20 29 31 36 36 43 48]

Cumulative product:
[    4    32   160   480  4320  8640 43200     0     0     0]

Discrete difference (n=3):
[  8   7 -21  23 -18  20 -21]

Unique elements:
[0 2 3 4 5 7 8 9]


Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [10]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Perform addition using zip()
addition_zip = [x + y for x, y in zip(array1, array2)]
print("Addition using zip():")
print(addition_zip)

# Perform addition using numpy.add()
addition_np = np.add(array1, array2)
print("Addition using numpy.add():")
print(addition_np)

# Define a user-defined addition function using numpy.frompyfunc()
def custom_add(x, y):
    return x + y

addition_custom = np.frompyfunc(custom_add, 2, 1)(array1, array2)
print("Addition using user-defined function (frompyfunc()):")
print(addition_custom)

Addition using zip():
[7, 9, 11, 13, 15]
Addition using numpy.add():
[ 7  9 11 13 15]
Addition using user-defined function (frompyfunc()):
[7 9 11 13 15]


Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce()

In [11]:
from functools import reduce
import math

# Define a function to find the LCM of two numbers
def lcm(x, y):
    return x * y // math.gcd(x, y)

# Define a function to find the GCD of two numbers
def gcd(x, y):
    return math.gcd(x, y)

# Example array of elements
array = [12, 18, 24, 36]

# Find the LCM of the elements in the array
lcm_result = reduce(lcm, array)

# Find the GCD of the elements in the array
gcd_result = reduce(gcd, array)

print("Array:", array)
print("LCM of the elements:", lcm_result)
print("GCD of the elements:", gcd_result)

Array: [12, 18, 24, 36]
LCM of the elements: 72
GCD of the elements: 6
