Array Indexing and Fancy Indexing

In [2]:
import numpy as np

X = np.array([1, 12, 31, 4, 50, 6, 7, 28,  9, 20])

print(X[4]) #returning the number in the fifth position


Y = np.array([1, 12, 31, 4, 50, 6, 7, 28,  9, 20])

Z = [0,3,4,7]

#fancy indexing
print(Y[Z])


50
[ 1  4 50 28]


2D Slicing of Array

In [19]:

array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])

print(array[0:3, 0:3],"\n")

subarray_2 = array[:, 1]  # All rows and Column 1
subarray_3 = array[1, :]  # Row 1 and All columns

print("Subarray 2:")
print(subarray_2,"\n")
print("Subarray 3:")
print(subarray_3)

[[1 2 3]
 [6 7 8]] 

Subarray 2:
[2 7] 

Subarray 3:
[ 6  7  8  9 10]


5-D ARRAY using ndmin

In [6]:
arr5D = np.array([1, 2, 3, 4], ndmin=5)

print(arr5D) 
print('shape of array :', arr5D.shape) # M×N columns and rows.    

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


Reshape the array from 1-D to 2-D array.

In [12]:
reshape_array = np.arange(0, 6)

reshaped_array = np.reshape(reshape_array, (2, 3)) # Reshape the array into a 2-D array with 2 rows and 3 columns

print(reshaped_array)

[[0 1 2]
 [3 4 5]]


Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack(). 

In [20]:
# Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().
import numpy as np

# Create sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# np.stack(): Stacking along a new axis
stacked_axis0 = np.stack((arr1, arr2), axis=0)
stacked_axis1 = np.stack((arr1, arr2), axis=1)

print("np.stack() along axis 0:")
print(stacked_axis0)
print("\nnp.stack() along axis 1:")
print(stacked_axis1)

# np.hstack(): Stacking horizontally
hstacked = np.hstack((arr1, arr2))
print("\nnp.hstack():")
print(hstacked)

# np.vstack(): Stacking vertically
vstacked = np.vstack((arr1, arr2))
print("\nnp.vstack():")
print(vstacked)

# Create 2D arrays
arr3 = np.array([[7], [8], [9]])
arr4 = np.array([[10], [11], [12]])

# np.dstack(): Stacking along the third axis (depth-wise)
dstacked = np.dstack((arr3, arr4))
print("\nnp.dstack():")
print(dstacked)


np.stack() along axis 0:
[[1 2 3]
 [4 5 6]]

np.stack() along axis 1:
[[1 4]
 [2 5]
 [3 6]]

np.hstack():
[1 2 3 4 5 6]

np.vstack():
[[1 2 3]
 [4 5 6]]

np.dstack():
[[[ 7 10]]

 [[ 8 11]]

 [[ 9 12]]]


Perform the searchsort method in Numpy array.


In [21]:
sort_array = np.array([3, 1, 2, 5, 4])

# Sort the array
sorted_arr = np.sort(sort_array)

print("Original array:")
print(sort_array)
print("Sorted array:")
print(sorted_arr)

Original array:
[3 1 2 5 4]
Sorted array:
[1 2 3 4 5]


Create Numpy Structured array using your domain features.


In [4]:
# Create Numpy Structured array using your domain features.
import numpy as np

# Define the data types for esports mgmt website features
feature_dtype = np.dtype([
    ('Player_Name', 'U50'),         #unicode string 50 chars
    ('Team', 'U50'),             
    ('Age', 'i4'),                  #32 bit integer
    ('Salary_per_month', 'i8'),     #64 bit integer
    ('Is_Active', bool)   
])

# Create an empty structured array with the defined data type
Team_features = np.array([], dtype=feature_dtype)

# Add website features to the structured array
player1 = ('TenZ','Sentinels',22,100000,True)
player2 = ('ShahzaM','Sentinels',24,100000,False)
player3 = ('Shroud','Sentinels',32,300000,False)

Team_features = np.array([player1, player2, player3], dtype=feature_dtype)

# Access and manipulate the structured array
print("Structured Array:")
print(Team_features)

# Accessing individual features
print("\nFirst PLAYER:")
print("Player Name:", Team_features['Player_Name'][0])
print("Player Team:", Team_features['Team'][0])
print("Player Age:", Team_features['Age'][0])
print("Player Salary", Team_features['Salary_per_month'][0])
print("Player Is Active:", Team_features['Is_Active'][0])


Structured Array:
[('TenZ', 'Sentinels', 22, 100000,  True)
 ('ShahzaM', 'Sentinels', 24, 100000, False)
 ('Shroud', 'Sentinels', 32, 300000, False)]

First PLAYER:
Player Name: TenZ
Player Team: Sentinels
Player Age: 22
Player Salary 100000
Player Is Active: True


Create Data frame using List and Dictionary

In [25]:
import pandas as pd

# Create a list of data
data_list = [
    ['Shawn', 21],
    ['Sid', 23],
    ['Shivanshi', 21]
]

# Create a DataFrame from the list
df_list = pd.DataFrame(data_list, columns=['Name', 'Age'])

# Display the DataFrame
print(df_list,"\n")


# Create a dictionary of data
data_dict = {
    'Name': ['Shawn', 'Sid', 'Shivanshi'],
    'Age': [21, 23, 21]
}

# Create a DataFrame from the dictionary
df_dict = pd.DataFrame(data_dict)

# Display the DataFrame
print(df_dict)

        Name  Age
0      Shawn   21
1        Sid   23
2  Shivanshi   21 

        Name  Age
0      Shawn   21
1        Sid   23
2  Shivanshi   21


Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
 • isnull()
 • notnull()
 • dropna()
 • fillna()
 • replace()
 • interpolate()

In [1]:

import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'ID': [1, 2, 3, 4, 5],
    'Player': ['TenZ', 'ShahzaM', np.nan, 'DapR', 'Shroud'],
    'Age': ['22', '28', np.nan, np.nan, '32'],
    'Game': ['Valorant', 'CSGO',  np.nan, 'Valorant', 'PUBG'],
    'Streamed_Platform': ['Twitch', 'Twitch', np.nan, 'Youtube', 'Twitch']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)
# isnull()
# Identify missing values

missing_data = df.isnull()
print("\nMissing Data (isnull()):")
print(missing_data)


# dropna
# Remove rows with missing values
df_clean = df.dropna()
print("\nDataFrame after dropna():")
print(df_clean)

# fillna
# Replace missing values with a default value
df_filled = df.fillna('No Data')
print("\nDataFrame after fillna():")
print(df_filled)

# replace()
# Replace specific values
df_replaced = df.replace('DapR', 'Hunter')
print("\nDataFrame after replace():")
print(df_replaced)

# interpolate
# Interpolate missing values
df_interpolated = df.interpolate()
print("\nDataFrame after interpolate():")
print(df_interpolated)



Original DataFrame:
   ID   Player  Age      Game Streamed_Platform
0   1     TenZ   22  Valorant            Twitch
1   2  ShahzaM   28      CSGO            Twitch
2   3      NaN  NaN       NaN               NaN
3   4     DapR  NaN  Valorant           Youtube
4   5   Shroud   32      PUBG            Twitch

Missing Data (isnull()):
      ID  Player    Age   Game  Streamed_Platform
0  False   False  False  False              False
1  False   False  False  False              False
2  False    True   True   True               True
3  False   False   True  False              False
4  False   False  False  False              False

DataFrame after dropna():
   ID   Player Age      Game Streamed_Platform
0   1     TenZ  22  Valorant            Twitch
1   2  ShahzaM  28      CSGO            Twitch
4   5   Shroud  32      PUBG            Twitch

DataFrame after fillna():
   ID   Player      Age      Game Streamed_Platform
0   1     TenZ       22  Valorant            Twitch
1   2  ShahzaM      

C:\Users\shawn\AppData\Local\Temp\ipykernel_7748\666449011.py:46: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


In [11]:
# replace()
# Replace specific values
df_replaced = df.replace('DapR', 'Hunter')
print("\nDataFrame after replace():")
print(df_replaced)



DataFrame after replace():
         Player      Game Streamed_Platform
ID Age                                     
1  22      TenZ  Valorant            Twitch
2  28   ShahzaM      CSGO            Twitch
3  NaN      NaN       NaN               NaN
4  NaN   Hunter  Valorant           Youtube
5  32    Shroud      PUBG            Twitch


Perform the Hierarchical Indexing in the above created dataset.


In [9]:
data = {
    'ID': [1, 2, 3, 4, 5],
    'Player': ['TenZ', 'ShahzaM', np.nan, 'DapR', 'Shroud'],
    'Age': ['22', '28', np.nan, np.nan, '32'],
    'Game': ['Valorant', 'CSGO',  np.nan, 'Valorant', 'PUBG'],
    'Streamed_Platform': ['Twitch', 'Twitch', np.nan, 'Youtube', 'Twitch']
}

dfnew = pd.DataFrame(data)

# Create hierarchical indexing
dfnew.set_index(['ID', 'Age'], inplace=True)

# Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:\n")
print(dfnew)

DataFrame with Hierarchical Indexing:

         Player      Game Streamed_Platform
ID Age                                     
1  22      TenZ  Valorant            Twitch
2  28   ShahzaM      CSGO            Twitch
3  NaN      NaN       NaN               NaN
4  NaN     DapR  Valorant           Youtube
5  32    Shroud      PUBG            Twitch
